# TBChanged # path or URL to sample sheet (TSV format, columns: sample, condition, ...)
metadata: "metadata/metadata.tsv"

# To be changed accordingly
## path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
## Units are technical replicates (e.g. lanes, or resequencing of the same biological
## sample).

# pypette output
# samples_csv: "pypette/samples/all/runs/all/samples.csv"

# test singlerun
# samples_csv: "config/samplesTestFast.csv"
# samples_csv: "config/samplesTestFast02.csv"

# test multirun
samples_csv: "config/samplesTestFast02_tinyTest_singlerun.csv"
# samples_csv: "config/samplesTest03_human.csv"
# samples_csv: "config/samplesTest03_mouse.csv"
# samples_csv: "config/samplesTestFast02_tinyTest.csv"

# env_cellranger: "/opt/common/tools/ric.cosr/miniconda3/envs/demux"
# to use this remember to specify the conda prefix in the profile
env_cellranger: "demux"
# env_cellbender: "/home/pedrini.edoardo/miniconda3/envs/env_cellbender_pip"
env_cellbender: "../envs/env_cellbender_pip.yaml"
env_velocyto: "../envs/env_velocyto.yaml"
# env_bioinfo: "/home/pedrini.edoardo/miniconda3/envs/env_bioinfo_minimal"
env_bioinfo: "../envs/env_bioinfo_minimal.yaml"
env_seurat: "../envs/env_R_COSR.yaml"
env_testR: "../envs/env_testR.yaml"
env_annotationCyteTypeR: "../envs/env_cytetypeR.yaml"

# were to save the output of the processing
out_location: "results/"

INTRON_param: '--include-introns'
INTRON_flag: 'true'
BAM_flag: 'true'

# memory parameters required for resources assignment
# in "integrateSamples" rule
memory_per_cell: 1        # MB per cell
max_mem_mb: 300000        # MB

# add flag to run cellbender or not. Set to False to skip cellbender
# run_cellbender: True
run_cellbender: False

# add flag to run velocity or not. Set to False to skip velocity
# run_velocity: True
run_velocity: False

# json containing the metadata for the annotation step
meta_annotation: "config/meta_annotation.json"

# token for the annotation step
# token_CyteTypeR: ""
# now this has been set as an environment variable

# covariate used in the annotation step
cov_markers_CyteTypeR: "RNA_snn_res.0.3"

Seurat:
  embedding:
    n_dims: 30
    resolutions: [.3, .6, 1, 1.2]
  markers: 
    min_pct: .1
    
report:
  figure_extension: ['pdf', 'png']
  qc_features: ['nFeature_RNA','nCount_RNA','percent.mt','percent.ribo','percent.globin','scDblFinder.score']

ref:
  # Ensembl species name
  species: homo_sapiens
  # species: mus_musculus
  # Gencode release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 45
  # Genome build
  build: GRCh38
  database: gencode
  organism_id: 9606
  # organism_id: 10090
  animal: human
  # Path to the reference genome for Cell Ranger (e.g., GRCh38 or mm10)
  # test tiny
  # reference: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/reference/cellranger_tiny_ref"
  # reference: "/beegfs/datasets/buffer/ric.cosr/cellranger/GRCh38_2024-A/GRCh38"
  repeat_mask_gtf: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/reference/repeat_mask_GRCh38.gtf"
  # reference: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/reference/refdata-gex-GRCm39-2024-A"
  reference: "/idle/ric.cosr/ric.cosr/pedrini.edoardo/reference/refdata-gex-GRCh38-2024-A"
  reference_gtf: "/beegfs/scratch/ric.cosr/ric.brendolan/BrendolanA_2629_scRNAseq_Only_Seq/GRCm39_2024-A/GRCm39/genes/genes.gtf"
  reference_fasta: "/beegfs/scratch/ric.cosr/ric.brendolan/BrendolanA_2629_scRNAseq_Only_Seq/GRCm39_2024-A/GRCm39/fasta/genome.fa"
trans: 
  # reference: "/beegfs/datasets/buffer/ric.cosr/cellranger_genomes/refdata-gex-mm10-2020-A"
  transgene_fasta: "/beegfs/scratch/ric.cosr/ric.brendolan/BrendolanA_2629_scRNAseq_Only_Seq/TdTomato.upper.fa"
  transgene_name: "TdTomato"

# ======================================================================
# == test benchmark ==
# ======================================================================

# benchmark locations
location_benchmark_obj: "workflow/test/R_code/out/object/test_human_default/"
location_benchmark_plot: "workflow/test/R_code/out/plot/test_human_default/"
location_benchmark_table: "workflow/test/R_code/out/table/test_human_default/"

# resolutions to be tested
resolutions: ["RNA_snn_res.0.3"]

# hardcode the sample name for the integration benchmark test
sample_benchmark:
  - 'connect_5k_pbmc_NGSC3_ch1_gex'
  - '5k_Human_Donor1_PBMC_3p_gem-x_GEX'
  - '5k_human_jejunum_CNIK_3pv3'
  - 'Brain_Tumor_3p'
  - 'Breast_Cancer_3p'
  - 'SC3_v3_NextGem_DI_CRISPR_A549_5K_gex'